schema_version: 1

context:
  name: norwegianblue
  version: "0.24.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/norwegianblue-${{ version }}.tar.gz
  sha256: 322a5728ce437d6e1571bce726b9e3391cc7ebbb0f48e0f6361666464562a828

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - eol = norwegianblue.cli:main
      - norwegianblue = norwegianblue.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatch-vcs
    - hatchling >=1.27
    - pip
  run:
    - python >=${{ python_min }}
    - argcomplete >=3.4
    - httpx >=0.19
    - platformdirs
    - prettytable >=3.16
    - pytablewriter >=0.63
    # from pytablewriter[html]
    - dominate >=2.1.5
    - python-dateutil
    - python-slugify
    - termcolor >=2.1

tests:
  - python:
      imports:
        - norwegianblue
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - eol --help
      - norwegianblue --help

about:
  license: MIT
  license_file: LICENSE.txt
  summary: CLI to show end-of-life dates for a number of products
  homepage: https://github.com/hugovk/norwegianblue
  repository: https://github.com/hugovk/norwegianblue
  documentation: https://endoflife.date/

extra:
  recipe-maintainers:
    - matthewfeickert
